"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateSupabaseJWT = generateSupabaseJWT;
exports.isValidJWTFormat = isValidJWTFormat;
exports.generateKongConfig = generateKongConfig;
exports.regenerateSupabaseKongConfig = regenerateSupabaseKongConfig;
exports.fixSupabaseStudioPort = fixSupabaseStudioPort;
exports.ensureSupabaseGoTrueMigrations = ensureSupabaseGoTrueMigrations;
exports.ensureSupabaseGoTrueDbNamespace = ensureSupabaseGoTrueDbNamespace;
exports.applySupabaseFullSmtpEnvVars = applySupabaseFullSmtpEnvVars;
exports.ensureSupabaseFullSmtpMapping = ensureSupabaseFullSmtpMapping;
exports.ensureSupabaseFullDbAccess = ensureSupabaseFullDbAccess;
const crypto_1 = require("crypto");
const db_1 = require("../../db");
/**
 * Generate a Supabase JWT token for API authentication
 * Used for ANON_KEY and SERVICE_ROLE_KEY generation
 */
function generateSupabaseJWT(secret, role) {
    const header = { alg: 'HS256', typ: 'JWT' };
    const now = Math.floor(Date.now() / 1000);
    const tenYearsInSeconds = 10 * 365 * 24 * 60 * 60;
    const payload = { role, iss: 'supabase', iat: now, exp: now + tenYearsInSeconds };
    const base64UrlEncode = (obj) => {
        const json = JSON.stringify(obj);
        const base64 = Buffer.from(json).toString('base64');
        return base64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
    };
    const encodedHeader = base64UrlEncode(header);
    const encodedPayload = base64UrlEncode(payload);
    const signatureInput = `${encodedHeader}.${encodedPayload}`;
    const signature = (0, crypto_1.createHmac)('sha256', secret)
        .update(signatureInput)
        .digest('base64')
        .replace(/\+/g, '-')
        .replace(/\//g, '_')
        .replace(/=+$/, '');
    return `${signatureInput}.${signature}`;
}
/**
 * Check if a string is a valid JWT format (3 base64url segments separated by dots)
 */
function isValidJWTFormat(token) {
    if (!token || typeof token !== 'string')
        return false;
    const parts = token.split('.');
    if (parts.length !== 3)
        return false;
    return parts.every(part => part.length > 0 && /^[A-Za-z0-9_-]+$/.test(part));
}
/**
 * Generate Kong declarative configuration for Supabase Full stack
 */
function generateKongConfig(envVars) {
    const dashboardUsername = envVars.DASHBOARD_USERNAME || 'admin';
    const dashboardPassword = envVars.DASHBOARD_PASSWORD || '';
    const anonKey = envVars.ANON_KEY || '';
    const serviceRoleKey = envVars.SERVICE_ROLE_KEY || '';
    return `# Kong Declarative Configuration for Supabase
# Auto-generated by ServerCompass

_format_version: "2.1"
_transform: true

consumers:
  - username: anon
    keyauth_credentials:
      - key: "${anonKey}"
  - username: service_role
    keyauth_credentials:
      - key: "${serviceRoleKey}"
  - username: DASHBOARD
    basicauth_credentials:
      - username: "${dashboardUsername}"
        password: "${dashboardPassword}"

acls:
  - consumer: anon
    group: anon
  - consumer: service_role
    group: admin

services:
  # REST API (PostgREST)
  - name: rest-v1
    url: http://rest:3000/
    routes:
      - name: rest-v1-route
        strip_path: true
        paths:
          - /rest/v1/
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: true
      - name: acl
        config:
          hide_groups_header: true
          allow:
            - admin
            - anon

  # Auth API (GoTrue)
  - name: auth-v1
    url: http://auth:9999/
    routes:
      - name: auth-v1-route
        strip_path: true
        paths:
          - /auth/v1/
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: true
      - name: acl
        config:
          hide_groups_header: true
          allow:
            - admin
            - anon

  # Realtime (WebSocket)
  - name: realtime-v1
    url: http://realtime:4000/socket
    routes:
      - name: realtime-v1-route
        strip_path: true
        paths:
          - /realtime/v1/
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: true
      - name: acl
        config:
          hide_groups_header: true
          allow:
            - admin
            - anon

  # Database Meta (for Studio)
  - name: meta
    url: http://meta:8080/
    routes:
      - name: meta-route
        strip_path: true
        paths:
          - /pg/
    plugins:
      - name: key-auth
        config:
          hide_credentials: true
      - name: acl
        config:
          hide_groups_header: true
          allow:
            - admin

  # Studio Dashboard (protected by basic auth)
  - name: dashboard
    url: http://studio:3000/
    routes:
      - name: dashboard-route
        strip_path: true
        paths:
          - /
    plugins:
      - name: cors
      - name: basic-auth
        config:
          hide_credentials: true
`;
}
/**
 * Regenerate Kong config for Supabase Full stack during redeploy
 */
async function regenerateSupabaseKongConfig(deps, serverId, workingDir, envVars, stackId) {
    if (!envVars.ANON_KEY || !envVars.SERVICE_ROLE_KEY || !envVars.DASHBOARD_PASSWORD) {
        deps.emitLog('⚠️ Skipping Kong config regeneration - missing required keys', 'warning', stackId);
        return;
    }
    const kongConfig = generateKongConfig(envVars);
    await deps.uploadFile(serverId, `${workingDir}/kong.yml`, kongConfig);
    deps.emitLog('✅ Kong API Gateway configuration updated', 'success', stackId);
    deps.emitLog('Restarting Kong to apply new credentials...', 'info', stackId);
    const restartResult = await deps.sshService.executeCommand(serverId, `cd ${workingDir} && docker compose restart kong`);
    if (restartResult.exitCode === 0) {
        deps.emitLog('✅ Kong restarted with new credentials', 'success', stackId);
    }
    else {
        deps.emitLog(`⚠️ Kong restart returned exit code ${restartResult.exitCode}: ${restartResult.stderr || restartResult.stdout}`, 'warning', stackId);
    }
}
/**
 * Fix Supabase Studio PORT configuration
 * Studio MUST listen on port 3000 (Kong routes to http://studio:3000/)
 * Without explicit PORT=3000, Studio inherits PORT=8000 from .env and causes "502 invalid upstream" error
 */
async function fixSupabaseStudioPort(deps, serverId, workingDir, stackId) {
    const composePath = `${workingDir}/docker-compose.yml`;
    const readResult = await deps.sshService.executeCommand(serverId, `cat "${composePath}" 2>/dev/null || echo ""`);
    if (readResult.exitCode !== 0 || !readResult.stdout.trim()) {
        return;
    }
    let composeContent = readResult.stdout;
    if (composeContent.includes('PORT=3000') && composeContent.includes('studio:')) {
        return;
    }
    const studioEnvPattern = /(studio:[\\s\\S]*?environment:\\s*\\n)(\\s+- )/;
    const match = composeContent.match(studioEnvPattern);
    if (match) {
        const indent = match[2];
        composeContent = composeContent.replace(studioEnvPattern, `$1${indent}PORT=3000\\n${indent}`);
        await deps.uploadFile(serverId, composePath, composeContent);
        deps.emitLog('✅ Fixed Studio PORT=3000 in docker-compose.yml', 'success', stackId);
        db_1.queries.updateDockerStack(stackId, { compose_content: composeContent });
    }
}
/**
 * Ensure Supabase GoTrue runs migrations at startup
 */
async function ensureSupabaseGoTrueMigrations(deps, serverId, workingDir, stackId) {
    const composePath = `${workingDir}/docker-compose.yml`;
    const readResult = await deps.sshService.executeCommand(serverId, `cat "${composePath}" 2>/dev/null || echo ""`);
    if (readResult.exitCode !== 0 || !readResult.stdout.trim()) {
        return;
    }
    let composeContent = readResult.stdout;
    if (composeContent.includes('gotrue migrate')) {
        return;
    }
    const authImagePattern = /(\n  auth:\n\s+image:\s*supabase\/gotrue:[^\n]+\n)/;
    if (!authImagePattern.test(composeContent)) {
        return;
    }
    composeContent = composeContent.replace(authImagePattern, `$1    command: ['/bin/sh', '-c', 'gotrue migrate && gotrue serve']\n`);
    await deps.uploadFile(serverId, composePath, composeContent);
    deps.emitLog('✅ Enabled GoTrue migrations (gotrue migrate) for Supabase Auth', 'success', stackId);
    db_1.queries.updateDockerStack(stackId, { compose_content: composeContent });
}
/**
 * Ensure GoTrue uses the `auth` schema for its tables.
 */
async function ensureSupabaseGoTrueDbNamespace(deps, serverId, workingDir, stackId) {
    const composePath = `${workingDir}/docker-compose.yml`;
    const readResult = await deps.sshService.executeCommand(serverId, `cat "${composePath}" 2>/dev/null || echo ""`);
    if (readResult.exitCode !== 0 || !readResult.stdout.trim()) {
        return;
    }
    let composeContent = readResult.stdout;
    if (composeContent.includes('DB_NAMESPACE=auth')) {
        return;
    }
    const authDatabaseUrlPattern = /(\\n  auth:\\n[\\s\\S]*?\\n\\s*-\\s*DATABASE_URL=[^\\n]*\\n)/;
    if (!authDatabaseUrlPattern.test(composeContent)) {
        return;
    }
    composeContent = composeContent.replace(authDatabaseUrlPattern, `$1      - DB_NAMESPACE=auth\\n`);
    await deps.uploadFile(serverId, composePath, composeContent);
    deps.emitLog('✅ Set DB_NAMESPACE=auth for GoTrue', 'success', stackId);
    db_1.queries.updateDockerStack(stackId, { compose_content: composeContent });
}
function applySupabaseFullSmtpEnvVars(envVars, stackId, emitLog) {
    const smtpHost = (envVars.SMTP_HOST || '').trim();
    const smtpPortRaw = (envVars.SMTP_PORT || '').trim();
    const smtpUser = (envVars.SMTP_USER || '').trim();
    const smtpPass = (envVars.SMTP_PASS || '').trim();
    const senderEmail = (envVars.SMTP_SENDER_EMAIL || '').trim();
    const senderName = (envVars.SMTP_SENDER_NAME || '').trim();
    const gotrueKeys = [
        'GOTRUE_SMTP_ADMIN_EMAIL',
        'GOTRUE_SMTP_HOST',
        'GOTRUE_SMTP_PORT',
        'GOTRUE_SMTP_PASS',
        'GOTRUE_SMTP_USER',
        'GOTRUE_SMTP_SENDER_NAME',
    ];
    let changed = false;
    const set = (key, value) => {
        if (envVars[key] !== value) {
            envVars[key] = value;
            changed = true;
        }
    };
    const del = (key) => {
        if (key in envVars) {
            delete envVars[key];
            changed = true;
        }
    };
    if (!smtpHost) {
        for (const key of gotrueKeys)
            del(key);
        return changed;
    }
    set('GOTRUE_SMTP_HOST', smtpHost);
    const portCandidate = smtpPortRaw ? Number.parseInt(smtpPortRaw, 10) : 587;
    if (!Number.isFinite(portCandidate)) {
        emitLog?.(`⚠️ SMTP_PORT is not a number (${JSON.stringify(smtpPortRaw)}). GoTrue requires an integer port.`, 'warning', stackId);
    }
    else {
        set('GOTRUE_SMTP_PORT', String(portCandidate));
    }
    if (smtpUser)
        set('GOTRUE_SMTP_USER', smtpUser);
    if (smtpPass)
        set('GOTRUE_SMTP_PASS', smtpPass);
    if (senderEmail)
        set('GOTRUE_SMTP_ADMIN_EMAIL', senderEmail);
    if (senderName)
        set('GOTRUE_SMTP_SENDER_NAME', senderName);
    return changed;
}
/**
 * Ensure Supabase Full doesn't override GoTrue SMTP env vars in docker-compose.yml
 */
async function ensureSupabaseFullSmtpMapping(deps, serverId, workingDir, envVars, stackId) {
    const composePath = `${workingDir}/docker-compose.yml`;
    const readResult = await deps.sshService.executeCommand(serverId, `cat "${composePath}" 2>/dev/null || echo ""`);
    if (readResult.exitCode !== 0 || !readResult.stdout.trim()) {
        return;
    }
    let composeContent = readResult.stdout;
    const beforeCompose = composeContent;
    composeContent = composeContent.replace(/^\\s*-\\s*GOTRUE_SMTP_(?:ADMIN_EMAIL|HOST|PORT|PASS|USER|SENDER_NAME)=.*\\r?\\n/gm, '');
    const composeChanged = composeContent !== beforeCompose;
    const envChanged = applySupabaseFullSmtpEnvVars(envVars, stackId, deps.emitLog);
    if (!composeChanged && !envChanged)
        return;
    if (composeChanged) {
        await deps.uploadFile(serverId, composePath, composeContent);
        db_1.queries.updateDockerStack(stackId, { compose_content: composeContent });
        deps.emitLog('✅ Removed GoTrue SMTP overrides from docker-compose.yml', 'success', stackId);
    }
    if (envChanged) {
        await deps.createEnvFile(serverId, workingDir, envVars);
        db_1.queries.updateDockerStack(stackId, { env_vars: JSON.stringify(envVars) });
        deps.emitLog('✅ Synced GoTrue SMTP env vars from SMTP_*', 'success', stackId);
    }
    const restartResult = await deps.sshService.executeCommand(serverId, `cd ${workingDir} && docker compose restart auth`);
    if (restartResult.exitCode === 0) {
        deps.emitLog('✅ Restarted auth to apply SMTP changes', 'success', stackId);
    }
    else {
        deps.emitLog(`⚠️ auth restart returned exit code ${restartResult.exitCode}: ${restartResult.stderr || restartResult.stdout}`, 'warning', stackId);
    }
}
/**
 * Ensure Supabase Full DB roles/search_path/grants are set for Auth + Meta
 */
async function ensureSupabaseFullDbAccess(deps, serverId, workingDir, stackId) {
    const sql = `
CREATE SCHEMA IF NOT EXISTS auth;

ALTER ROLE supabase_auth_admin SET search_path TO auth, public;
ALTER ROLE supabase_admin SET search_path TO public, auth;

GRANT USAGE ON SCHEMA auth TO supabase_admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA auth TO supabase_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA auth TO supabase_admin;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA auth TO supabase_admin;

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_auth_admin IN SCHEMA auth GRANT ALL ON TABLES TO supabase_admin;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_auth_admin IN SCHEMA auth GRANT ALL ON SEQUENCES TO supabase_admin;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_auth_admin IN SCHEMA auth GRANT ALL ON FUNCTIONS TO supabase_admin;
`.trim();
    deps.emitLog('Ensuring Supabase Full DB access (auth schema grants + search_path)...', 'info', stackId);
    const applySqlResult = await deps.sshService.executeCommand(serverId, `cd ${workingDir} && docker compose exec -T db psql -U postgres -d postgres -v ON_ERROR_STOP=1 << 'SERVERCOMPASS_SQL'\n${sql}\nSERVERCOMPASS_SQL`);
    if (applySqlResult.exitCode !== 0) {
        deps.emitLog(`⚠️ Could not apply Supabase DB grants/search_path: ${applySqlResult.stderr || applySqlResult.stdout}`, 'warning', stackId);
        return;
    }
    deps.emitLog('✅ Supabase Full DB access updated (auth schema + search_path)', 'success', stackId);
    const restartResult = await deps.sshService.executeCommand(serverId, `cd ${workingDir} && docker compose restart auth meta`);
    if (restartResult.exitCode === 0) {
        deps.emitLog('✅ Restarted auth + meta to apply DB access changes', 'success', stackId);
    }
    else {
        deps.emitLog(`⚠️ Restart auth/meta returned exit code ${restartResult.exitCode}: ${restartResult.stderr || restartResult.stdout}`, 'warning', stackId);
    }
}
//# sourceMappingURL=supabase.js.map