"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createGitHubActionsDockerService = exports.GitHubActionsDockerService = void 0;
const fs_1 = require("fs");
const path_1 = require("path");
const os_1 = require("os");
const child_process_1 = require("child_process");
const db_1 = require("../db");
const GitHubApiService_1 = require("./GitHubApiService");
const CredentialVault_1 = require("./CredentialVault");
const ExternalBuildDeploymentService_1 = require("./build/ExternalBuildDeploymentService");
class GitHubActionsDockerService {
    static GENERATED_DOCKERFILE_MARKER = '# Generated by ServerCompass';
    githubApi = new GitHubApiService_1.GitHubApiService();
    sshService;
    vault = new CredentialVault_1.CredentialVault();
    externalBuildDeploymentService = new ExternalBuildDeploymentService_1.ExternalBuildDeploymentService();
    constructor(sshService) {
        this.sshService = sshService;
    }
    /**
     * Get OAuth token for a git account
     */
    async getOAuthToken(gitAccountId) {
        try {
            const account = db_1.db.prepare(`
        SELECT encrypted_token FROM git_accounts WHERE id = ?
      `).get(gitAccountId);
            if (!account || !account.encrypted_token || account.encrypted_token.length === 0) {
                console.warn('[GitHubActionsDockerService] No encrypted token found for git account:', gitAccountId);
                return null;
            }
            const token = await this.vault.decrypt(account.encrypted_token);
            return token;
        }
        catch (error) {
            console.error('[GitHubActionsDockerService] Failed to get OAuth token:', error);
            return null;
        }
    }
    /**
     * Generate SSH key pair locally (without requiring VPS access)
     */
    generateSSHKeyLocally(projectName) {
        const sanitizedAppName = projectName.toLowerCase().replace(/[^a-z0-9-]/g, '-');
        const tempDir = (0, path_1.join)((0, os_1.tmpdir)(), `servercompass-${Date.now()}`);
        const keyPath = (0, path_1.join)(tempDir, `id_ed25519_deploy_${sanitizedAppName}`);
        try {
            // Create temp directory
            (0, fs_1.mkdirSync)(tempDir, { recursive: true });
            // Generate Ed25519 SSH key pair
            (0, child_process_1.execSync)(`ssh-keygen -t ed25519 -f "${keyPath}" -N "" -C "servercompass-deploy-${sanitizedAppName}"`, { stdio: 'pipe' });
            // Read private key
            const privateKey = (0, fs_1.readFileSync)(keyPath, 'utf-8').trim();
            // Read public key
            const publicKey = (0, fs_1.readFileSync)(`${keyPath}.pub`, 'utf-8').trim();
            // Clean up temp files
            (0, fs_1.rmSync)(tempDir, { recursive: true, force: true });
            console.log('[GitHubActionsDockerService] Generated SSH key locally');
            return { privateKey, publicKey };
        }
        catch (error) {
            // Clean up on error
            try {
                (0, fs_1.rmSync)(tempDir, { recursive: true, force: true });
            }
            catch { }
            throw error;
        }
    }
    /**
     * Format GitHub API errors into user-friendly messages
     */
    formatGitHubError(error) {
        // Rate limit error
        if (error.status === 403 || error.status === 429) {
            const resetTime = error.response?.headers?.['x-ratelimit-reset'];
            const resetDate = resetTime ? new Date(parseInt(resetTime) * 1000) : null;
            const timeUntilReset = resetDate ? Math.ceil((resetDate.getTime() - Date.now()) / 60000) : null;
            let message = '🚫 GitHub API rate limit exceeded.\n\n';
            if (resetDate) {
                message += `⏰ Your rate limit will reset at ${resetDate.toLocaleTimeString()}`;
                if (timeUntilReset) {
                    message += ` (in about ${timeUntilReset} minute${timeUntilReset !== 1 ? 's' : ''})`;
                }
                message += '.\n\n';
            }
            message += '💡 What you can do:\n';
            message += '• Wait a few minutes and try again\n';
            message += '• Check your rate limit status at: https://github.com/settings/tokens\n';
            message += '• Consider using a personal access token with higher limits\n\n';
            message += 'ℹ️ GitHub limits API requests to 5,000 per hour for authenticated users.';
            return message;
        }
        // Authentication error
        if (error.status === 401) {
            return '🔐 GitHub authentication failed.\n\n' +
                'Please reconnect your GitHub account in Server Compass settings.';
        }
        // Permission error
        if (error.status === 404 && error.message?.includes('Not Found')) {
            return ('🔍 Not found (repo/branch) or access restricted.\n\n' +
                'Please check that:\n' +
                '• The repository exists and the owner/name is correct\n' +
                '• The branch exists (common mismatch: "main" vs "master")\n' +
                '• Your GitHub account has write access to the repo\n' +
                '• If this is an org repo: allow/approve the Server Compass OAuth app (and authorize SSO if required)');
        }
        // Network error
        if (error.code === 'ENOTFOUND' || error.code === 'ETIMEDOUT') {
            return '🌐 Network error: Unable to reach GitHub.\n\n' +
                'Please check your internet connection and try again.';
        }
        // Generic GitHub API error
        if (error.message) {
            return `❌ GitHub API Error: ${error.message}`;
        }
        // Unknown error
        return `❌ An unexpected error occurred: ${String(error)}`;
    }
    /**
     * Get workflow file path for Docker deployment
     */
    getWorkflowPath(projectName) {
        return `.github/workflows/server-compass-docker-${projectName}.yml`;
    }
    /**
     * Generate a workflow file preview (path + content) without committing anything.
     */
    previewWorkflowFile(config) {
        const containerPort = this.resolveContainerPort(config.dockerfileContent, config.port);
        const imageTag = (config.imageTag || 'latest').trim() || 'latest';
        return {
            path: this.getWorkflowPath(config.projectName),
            content: this.generateWorkflowContent({
                ...config,
                containerPort,
                dockerfilePath: config.dockerfilePath || 'Dockerfile',
                imageTag,
            }),
        };
    }
    /**
     * Resolve internal container port from Dockerfile EXPOSE.
     * Falls back to the selected app port, then 3000.
     */
    resolveContainerPort(dockerfileContent, fallbackPort) {
        if (dockerfileContent) {
            const match = dockerfileContent.match(/^\s*EXPOSE\s+(\d+)/im);
            if (match) {
                const parsed = Number.parseInt(match[1], 10);
                if (Number.isFinite(parsed) && parsed > 0 && parsed <= 65535) {
                    return parsed;
                }
            }
        }
        if (fallbackPort && fallbackPort > 0 && fallbackPort <= 65535) {
            return fallbackPort;
        }
        return 3000;
    }
    /**
     * Parse .env text into a JSON-friendly object for docker_stacks.env_vars persistence.
     * Returns null only when env content was not provided by caller.
     */
    parseEnvFileContent(envFileContent) {
        if (envFileContent === undefined)
            return null;
        const envVars = {};
        const lines = envFileContent.split(/\r?\n/);
        for (const line of lines) {
            const trimmed = line.trim();
            if (!trimmed || trimmed.startsWith('#'))
                continue;
            const separatorIndex = line.indexOf('=');
            if (separatorIndex <= 0)
                continue;
            const key = line.slice(0, separatorIndex).trim();
            if (!key)
                continue;
            envVars[key] = line.slice(separatorIndex + 1);
        }
        return envVars;
    }
    /**
     * Next.js exposes `NEXT_PUBLIC_*` at build time. For GitHub Build we need a safe
     * way to provide these to the Docker build without leaking server secrets.
     *
     * We extract only `NEXT_PUBLIC_*` assignments and store them base64-encoded as
     * a separate GitHub secret. The Dockerfile can decode it into an env file
     * before running `next build`.
     */
    encodeNextPublicEnvBase64(envFileContent) {
        const lines = envFileContent.split(/\r?\n/);
        const nextPublicLines = [];
        for (const line of lines) {
            const trimmed = line.trim();
            if (!trimmed || trimmed.startsWith('#'))
                continue;
            const separatorIndex = line.indexOf('=');
            if (separatorIndex <= 0)
                continue;
            const key = line.slice(0, separatorIndex).trim();
            if (!key.startsWith('NEXT_PUBLIC_'))
                continue;
            nextPublicLines.push(`${key}=${line.slice(separatorIndex + 1)}`);
        }
        const fileContent = nextPublicLines.length === 0
            ? '# ServerCompass: no NEXT_PUBLIC_* vars provided\n'
            : `${nextPublicLines.join('\n')}\n`;
        return Buffer.from(fileContent, 'utf8').toString('base64');
    }
    shellQuote(value) {
        return `'${value.replace(/'/g, `'\\''`)}'`;
    }
    extractPublishedHostPorts(portMappings) {
        const hostPorts = new Set();
        const matches = portMappings.matchAll(/(\d+)(?:-\d+)?->/g);
        for (const match of matches) {
            const parsed = Number.parseInt(match[1], 10);
            if (Number.isFinite(parsed) && parsed > 0 && parsed <= 65535) {
                hostPorts.add(parsed);
            }
        }
        return Array.from(hostPorts);
    }
    extractListeningPorts(networkOutput) {
        const ports = new Set();
        const lines = networkOutput.split('\n');
        for (const rawLine of lines) {
            const line = rawLine.trim();
            if (!line || /^State\b/i.test(line) || /^Active\b/i.test(line) || /^Proto\b/i.test(line)) {
                continue;
            }
            const match = line.match(/(?:\*|\[[^\]]+\]|[0-9a-fA-F:.]+):(\d+)\b/);
            if (!match)
                continue;
            const parsed = Number.parseInt(match[1], 10);
            if (Number.isFinite(parsed) && parsed > 0 && parsed <= 65535) {
                ports.add(parsed);
            }
        }
        return ports;
    }
    suggestAvailablePorts(usedPorts, desiredPort, limit = 3) {
        const suggestions = [];
        const seen = new Set();
        const pushCandidate = (port) => {
            if (!Number.isFinite(port) || port < 1 || port > 65535)
                return;
            if (usedPorts.has(port) || seen.has(port))
                return;
            seen.add(port);
            suggestions.push(port);
        };
        for (let port = desiredPort + 1; port <= desiredPort + 20 && suggestions.length < limit; port += 1) {
            pushCandidate(port);
        }
        const commonCandidates = [3000, 3001, 3002, 3003, 8080, 8000, 5000];
        for (const candidate of commonCandidates) {
            if (suggestions.length >= limit)
                break;
            pushCandidate(candidate);
        }
        for (let port = 3000; port <= 3999 && suggestions.length < limit; port += 1) {
            pushCandidate(port);
        }
        return suggestions;
    }
    async validateHostPortForInitialSetup(input) {
        const { serverId, projectName, port } = input;
        const dockerOwnersByPort = new Map();
        const containerComposeProjects = new Map(); // containerName -> composeProject
        const usedPorts = new Set();
        try {
            // Include compose project label to identify containers belonging to the same app
            const dockerResult = await this.sshService.executeCommand(serverId, `docker ps --format "{{.Names}}|{{.Ports}}|{{.Label \\"com.docker.compose.project\\"}}" 2>/dev/null || true`);
            const lines = dockerResult.stdout
                .split('\n')
                .map((line) => line.trim())
                .filter(Boolean);
            for (const line of lines) {
                const parts = line.split('|');
                if (parts.length < 2)
                    continue;
                const containerName = parts[0].trim();
                const portMappings = parts[1].trim();
                const composeProject = parts[2]?.trim() || '';
                const hostPorts = this.extractPublishedHostPorts(portMappings);
                if (composeProject) {
                    containerComposeProjects.set(containerName, composeProject);
                }
                for (const hostPort of hostPorts) {
                    usedPorts.add(hostPort);
                    const existingOwners = dockerOwnersByPort.get(hostPort) || [];
                    existingOwners.push(containerName);
                    dockerOwnersByPort.set(hostPort, existingOwners);
                }
            }
        }
        catch (error) {
            console.warn('[GitHubActionsDockerService] Failed to inspect docker published ports:', error);
        }
        try {
            const networkResult = await this.sshService.executeCommand(serverId, `(ss -ltn 2>/dev/null || netstat -ltn 2>/dev/null || true)`);
            const listeningPorts = this.extractListeningPorts(networkResult.stdout);
            for (const listeningPort of listeningPorts) {
                usedPorts.add(listeningPort);
            }
        }
        catch (error) {
            console.warn('[GitHubActionsDockerService] Failed to inspect listening ports:', error);
        }
        const dockerOwners = dockerOwnersByPort.get(port) || [];
        // Filter out containers that belong to the same compose project (handles VPS -> GitHub Actions switch)
        // or containers that start with the project name (fallback for containers without compose label)
        const blockingDockerOwners = dockerOwners.filter((owner) => {
            const ownerComposeProject = containerComposeProjects.get(owner);
            // Same compose project - this container will be replaced during deployment
            if (ownerComposeProject === projectName)
                return false;
            // Container name starts with project name (e.g., "myapp-vps", "myapp-app") - likely same app
            if (owner.startsWith(`${projectName}-`) || owner.startsWith(`${projectName}_`))
                return false;
            return true;
        });
        const blockedByUnknownListener = usedPorts.has(port) && dockerOwners.length === 0;
        return {
            available: blockingDockerOwners.length === 0 && !blockedByUnknownListener,
            blockingDockerOwners,
            blockedByUnknownListener,
            suggestedPorts: this.suggestAvailablePorts(usedPorts, port),
        };
    }
    ensureGeneratedDockerfileMarker(content) {
        const trimmed = content.trim();
        if (!trimmed)
            return '';
        if (trimmed.startsWith(GitHubActionsDockerService.GENERATED_DOCKERFILE_MARKER)) {
            return trimmed;
        }
        return `${GitHubActionsDockerService.GENERATED_DOCKERFILE_MARKER}\n${trimmed}`;
    }
    normalizeEnvFileHeredocIndentation(workflowContent) {
        return workflowContent.replace(/^([ \t]*)cat > \.env << 'SERVER_COMPASS_ENV_FILE'\n[ \t]*(\$\{\{ secrets\.ENV_FILE_[A-Z0-9_]+\}\})\n[ \t]*SERVER_COMPASS_ENV_FILE/gm, (_match, indent, secretReference) => `${indent}cat > .env << 'SERVER_COMPASS_ENV_FILE'\n` +
            `${indent}${secretReference}\n` +
            `${indent}SERVER_COMPASS_ENV_FILE`);
    }
    async logEnvSecretMetadata(repoOwner, repoName, secretName, username) {
        try {
            const metadata = await this.githubApi.getRepoSecretMetadata(repoOwner, repoName, secretName, username);
            console.log(`[GitHubActionsDockerService] ✅ Env secret synced: ${metadata.name} (updated ${metadata.updatedAt})`);
        }
        catch (error) {
            console.warn(`[GitHubActionsDockerService] ⚠️ Unable to verify env secret metadata for ${secretName}:`, error);
        }
    }
    /**
     * Generate docker-compose.yml content
     */
    generateDockerCompose(config) {
        const traefikNetworkBlock = config.includeTraefikPublicNetwork
            ? `    networks:
      - default
      - traefik-public

networks:
  traefik-public:
    external: true
`
            : '';
        return `services:
  ${config.projectName}:
    image: ghcr.io/${config.repoOwner}/${config.repoName}:${config.imageTag}
    container_name: ${config.projectName}-app
    ports:
      - "${config.port}:${config.containerPort}"
    environment:
      PORT: "\${PORT:-${config.containerPort}}"
    env_file:
      - .env
    restart: unless-stopped
${traefikNetworkBlock}
`;
    }
    /**
     * Generate GitHub Actions workflow content
     */
    generateWorkflowContent(config) {
        const templatePath = (0, path_1.join)(__dirname, '../templates/github-actions-docker-deploy.yml');
        let template = (0, fs_1.readFileSync)(templatePath, 'utf-8');
        const appNameUpper = config.projectName.toUpperCase().replace(/[^A-Z0-9]/g, '_');
        template = template.replace(/\{\{APP_NAME\}\}/g, config.projectName);
        template = template.replace(/\{\{APP_NAME_UPPER\}\}/g, appNameUpper);
        template = template.replace(/\{\{BRANCH\}\}/g, config.branch);
        template = template.replace(/\{\{WORKING_DIRECTORY\}\}/g, config.appPath);
        template = template.replace(/\{\{PORT\}\}/g, config.port.toString());
        template = template.replace(/\{\{CONTAINER_PORT\}\}/g, config.containerPort.toString());
        template = template.replace(/\{\{DOCKERFILE_PATH\}\}/g, config.dockerfilePath);
        template = template.replace(/\{\{IMAGE_TAG\}\}/g, config.imageTag);
        return template;
    }
    /**
     * Setup GitHub Actions Docker deployment
     */
    async setupDockerDeployment(config) {
        const { serverId, projectName, repoOwner, repoName, branch, appPath, port, gitAccountId, workflowContent, envFileContent, dockerfileContent: requestedDockerfileContent, retryDeployOnly = false, deployOnly = true, } = config;
        console.log(`[GitHubActionsDockerService] Setting up Docker deployment for ${projectName}...`);
        try {
            const dockerfilePath = 'Dockerfile';
            const resolvedDockerfileContent = this.ensureGeneratedDockerfileMarker(requestedDockerfileContent || '');
            const containerPort = this.resolveContainerPort(resolvedDockerfileContent, port);
            const imageTag = (config.imageTag || 'latest').trim() || 'latest';
            const parsedEnvVars = this.parseEnvFileContent(envFileContent);
            const envVarsJson = parsedEnvVars === null ? undefined : JSON.stringify(parsedEnvVars);
            const workflowPath = this.getWorkflowPath(projectName);
            const workflowFileName = workflowPath.split('/').pop() || workflowPath;
            const gitAccountRow = db_1.db
                .prepare('SELECT username FROM git_accounts WHERE id = ? LIMIT 1')
                .get(gitAccountId);
            if (!gitAccountRow) {
                throw new Error('Git account not found');
            }
            let resolvedBranch = branch;
            try {
                await this.githubApi.getBranchHeadSha(repoOwner, repoName, resolvedBranch, gitAccountRow.username);
            }
            catch (error) {
                if (error?.status !== 404) {
                    throw error;
                }
                try {
                    const defaultBranch = await this.githubApi.getRepoDefaultBranch(repoOwner, repoName, gitAccountRow.username);
                    if (defaultBranch && defaultBranch !== resolvedBranch) {
                        resolvedBranch = defaultBranch;
                        console.log(`[GitHubActionsDockerService] Branch "${branch}" not found; using default branch "${resolvedBranch}".`);
                    }
                }
                catch {
                    // If we can't read repo metadata, preserve the original 404 (could be access restriction).
                    throw error;
                }
            }
            if (!retryDeployOnly) {
                const portPreflight = await this.validateHostPortForInitialSetup({
                    serverId,
                    projectName,
                    port,
                });
                if (!portPreflight.available) {
                    const blockingSource = portPreflight.blockedByUnknownListener
                        ? 'another service on the server'
                        : `container(s): ${portPreflight.blockingDockerOwners.join(', ')}`;
                    const suggestionText = portPreflight.suggestedPorts.length > 0
                        ? ` Suggested available port(s): ${portPreflight.suggestedPorts.join(', ')}.`
                        : '';
                    return {
                        success: false,
                        error: `Host port ${port} is already in use by ${blockingSource}. ` +
                            `Choose a different App Port in the GitHub setup step and retry.${suggestionText}`,
                    };
                }
            }
            const composeContent = this.generateDockerCompose({
                projectName,
                repoOwner,
                repoName,
                port,
                containerPort,
                imageTag,
                includeTraefikPublicNetwork: config.includeTraefikPublicNetwork,
            });
            const { stackId, deploymentId } = this.externalBuildDeploymentService.ensureDeploymentRecord({
                serverId,
                projectName,
                sourceType: 'github',
                githubRepo: `${repoOwner}/${repoName}`,
                gitAccountId,
                gitBranch: resolvedBranch,
                appPath,
                composeContent,
                dockerfileContent: resolvedDockerfileContent || null,
                envVarsJson,
                triggerType: retryDeployOnly ? 'redeploy' : 'manual',
                provider: 'github-actions',
            });
            // Retry path: skip build setup/commit and dispatch workflow.
            if (retryDeployOnly) {
                console.log('[GitHubActionsDockerService] Triggering workflow dispatch (retry path)...');
                if (envFileContent !== undefined) {
                    const appNameUpper = projectName.toUpperCase().replace(/[^A-Z0-9]/g, '_');
                    const envSecretName = `ENV_FILE_${appNameUpper}`;
                    const nextPublicSecretName = `ENV_NEXT_PUBLIC_B64_${appNameUpper}`;
                    await this.githubApi.createOrUpdateSecret(repoOwner, repoName, envSecretName, envFileContent, gitAccountRow.username);
                    await this.logEnvSecretMetadata(repoOwner, repoName, envSecretName, gitAccountRow.username);
                    const nextPublicEnvB64 = this.encodeNextPublicEnvBase64(envFileContent);
                    await this.githubApi.createOrUpdateSecret(repoOwner, repoName, nextPublicSecretName, nextPublicEnvB64, gitAccountRow.username);
                    await this.logEnvSecretMetadata(repoOwner, repoName, nextPublicSecretName, gitAccountRow.username);
                }
                // Best-effort VPS sync so deploy job has a local .env fallback even if GitHub secret indexing lags.
                try {
                    await this.setupVPS({
                        serverId,
                        projectName,
                        repoOwner,
                        repoName,
                        appPath,
                        port,
                        containerPort,
                        envFileContent,
                        imageTag,
                        includeTraefikPublicNetwork: config.includeTraefikPublicNetwork,
                    });
                }
                catch (setupError) {
                    console.warn('[GitHubActionsDockerService] ⚠️ Could not sync VPS files before workflow dispatch:', setupError.message);
                }
                const triggeredAt = new Date().toISOString();
                const headSha = await this.githubApi.getBranchHeadSha(repoOwner, repoName, resolvedBranch, gitAccountRow.username);
                const inputs = deployOnly ? { deploy_only: 'true' } : undefined;
                await this.githubApi.triggerWorkflowDispatch(repoOwner, repoName, workflowFileName, resolvedBranch, gitAccountRow.username, inputs);
                return {
                    success: true,
                    data: {
                        stackId,
                        deploymentId,
                        workflowPath,
                        workflowFileName,
                        dockerfilePath,
                        commitSha: headSha,
                        triggerEvent: 'workflow_dispatch',
                        triggeredAt,
                    },
                };
            }
            // Step 1: Generate deployment SSH key locally (no VPS access needed)
            console.log('[GitHubActionsDockerService] Generating deployment SSH key locally...');
            const { privateKey, publicKey } = this.generateSSHKeyLocally(projectName);
            // Step 2: Upload public key to GitHub
            console.log('[GitHubActionsDockerService] Uploading SSH public key to GitHub...');
            const keyTitle = `ServerCompass-Docker-${projectName}-${Date.now()}`;
            await this.githubApi.uploadSSHKey(keyTitle, publicKey, gitAccountRow.username);
            // Step 3: Get VPS connection details
            const server = this.getServerDetails(serverId);
            // Step 4: Add public key to VPS authorized_keys
            console.log('[GitHubActionsDockerService] Adding deployment SSH key to VPS authorized_keys...');
            try {
                // Escape the public key for shell safety and ensure proper newline handling
                const escapedPublicKey = publicKey.replace(/'/g, "'\\''");
                // Add key with proper newline handling and deduplication
                const addKeyCommand = `
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys

          # Add newline if file doesn't end with one
          [ -s ~/.ssh/authorized_keys ] && [ -z "$(tail -c 1 ~/.ssh/authorized_keys)" ] || echo "" >> ~/.ssh/authorized_keys

          # Add key if not already present
          if ! grep -qF '${escapedPublicKey}' ~/.ssh/authorized_keys; then
            echo '${escapedPublicKey}' >> ~/.ssh/authorized_keys
            echo "Key added successfully"
          else
            echo "Key already exists"
          fi
        `.trim();
                const result = await this.sshService.executeCommand(serverId, addKeyCommand);
                if (result.exitCode === 0) {
                    console.log('[GitHubActionsDockerService] ✅ Deployment key added to VPS:', result.stdout);
                }
                else {
                    throw new Error(`Failed to add SSH key: ${result.stderr || result.stdout}`);
                }
            }
            catch (vpsError) {
                console.error('[GitHubActionsDockerService] ❌ Failed to add deployment key to VPS:', vpsError.message);
                throw new Error(`Cannot setup GitHub Actions deployment: Failed to add SSH key to VPS. ${vpsError.message}`);
            }
            // Step 5: Get GitHub OAuth token for GHCR authentication
            const ghcrToken = await this.getOAuthToken(gitAccountId);
            if (!ghcrToken) {
                throw new Error('Failed to retrieve GitHub OAuth token. Please reconnect your GitHub account.');
            }
            // Step 6: Upload secrets to GitHub
            console.log('[GitHubActionsDockerService] Uploading secrets to GitHub...');
            await this.uploadSecrets({
                repoOwner,
                repoName,
                projectName,
                vpsHost: server.host,
                vpsUser: server.username,
                vpsPort: server.port.toString(),
                vpsSSHKey: privateKey,
                ghcrUser: gitAccountRow.username,
                ghcrToken,
                envFileContent,
                username: gitAccountRow.username,
            });
            // Step 7: Commit workflow + Dockerfile files (if provided)
            console.log('[GitHubActionsDockerService] Committing files to repository...');
            const workflowFileContent = this.normalizeEnvFileHeredocIndentation(workflowContent ||
                this.generateWorkflowContent({
                    projectName,
                    branch: resolvedBranch,
                    appPath,
                    port,
                    containerPort,
                    dockerfilePath,
                    imageTag,
                }));
            const filesToCommit = [
                {
                    path: workflowPath,
                    content: workflowFileContent,
                },
            ];
            if (resolvedDockerfileContent) {
                filesToCommit.push({
                    path: dockerfilePath,
                    content: resolvedDockerfileContent,
                });
            }
            const triggeredAt = new Date().toISOString();
            const commitResult = await this.commitFiles(repoOwner, repoName, resolvedBranch, filesToCommit, gitAccountRow.username);
            // Always trigger workflow_dispatch for manual setup/redeploy actions.
            // Some repos won't start a push-triggered run immediately after creating/updating a workflow file.
            // The workflow template uses concurrency to prevent duplicate deployments if a push run also starts.
            console.log('[GitHubActionsDockerService] Triggering workflow_dispatch...');
            const dispatchInputs = undefined;
            const dispatchWithRetry = async () => {
                const maxAttempts = 3;
                for (let attempt = 1; attempt <= maxAttempts; attempt += 1) {
                    try {
                        await this.githubApi.triggerWorkflowDispatch(repoOwner, repoName, workflowFileName, resolvedBranch, gitAccountRow.username, dispatchInputs);
                        return;
                    }
                    catch (error) {
                        if (error?.status !== 404 || attempt === maxAttempts) {
                            throw error;
                        }
                        // Give GitHub a moment to index a newly-created workflow file.
                        await new Promise((resolve) => setTimeout(resolve, 2000));
                    }
                }
            };
            await dispatchWithRetry();
            const triggerEvent = 'workflow_dispatch';
            // Step 9: Create docker-compose.yml on VPS
            console.log('[GitHubActionsDockerService] Setting up VPS...');
            try {
                await this.setupVPS({
                    serverId,
                    projectName,
                    repoOwner,
                    repoName,
                    appPath,
                    port,
                    containerPort,
                    envFileContent,
                    imageTag,
                    includeTraefikPublicNetwork: config.includeTraefikPublicNetwork,
                });
                console.log('[GitHubActionsDockerService] ✅ VPS setup complete');
            }
            catch (setupError) {
                console.warn('[GitHubActionsDockerService] ⚠️ Could not setup docker-compose.yml on VPS (will be created by GitHub Actions):', setupError.message);
                console.warn('[GitHubActionsDockerService] The first deployment will create the necessary files');
                // Don't fail - GitHub Actions can create docker-compose.yml on first run
            }
            console.log(`[GitHubActionsDockerService] ✅ Deployment trigger ready (${triggerEvent}) ` +
                `for workflow ${workflowFileName}`);
            console.log(`[GitHubActionsDockerService] Successfully set up Docker deployment for ${projectName}`);
            return {
                success: true,
                data: {
                    stackId,
                    deploymentId,
                    workflowPath,
                    workflowFileName,
                    dockerfilePath,
                    commitSha: commitResult.commitSha,
                    triggerEvent,
                    triggeredAt,
                },
            };
        }
        catch (error) {
            console.error('[GitHubActionsDockerService] Failed to setup Docker deployment:', error);
            const userFriendlyError = this.formatGitHubError(error);
            return {
                success: false,
                error: userFriendlyError,
            };
        }
    }
    /**
     * Upload secrets to GitHub repository
     */
    async uploadSecrets(options) {
        const { repoOwner, repoName, projectName, vpsHost, vpsUser, vpsPort, vpsSSHKey, ghcrUser, ghcrToken, envFileContent, username } = options;
        const appNameUpper = projectName.toUpperCase().replace(/[^A-Z0-9]/g, '_');
        const secrets = [
            { name: `VPS_HOST_${appNameUpper}`, value: vpsHost },
            { name: `VPS_USER_${appNameUpper}`, value: vpsUser },
            { name: `VPS_PORT_${appNameUpper}`, value: vpsPort },
            { name: `VPS_SSH_KEY_${appNameUpper}`, value: vpsSSHKey },
            { name: `GHCR_USER_${appNameUpper}`, value: ghcrUser },
            { name: `GHCR_TOKEN_${appNameUpper}`, value: ghcrToken },
        ];
        if (envFileContent !== undefined) {
            secrets.push({ name: `ENV_FILE_${appNameUpper}`, value: envFileContent });
            secrets.push({
                name: `ENV_NEXT_PUBLIC_B64_${appNameUpper}`,
                value: this.encodeNextPublicEnvBase64(envFileContent),
            });
        }
        for (const secret of secrets) {
            console.log(`[GitHubActionsDockerService] Uploading secret: ${secret.name}`);
            await this.githubApi.createOrUpdateSecret(repoOwner, repoName, secret.name, secret.value, username);
        }
        if (envFileContent !== undefined) {
            await this.logEnvSecretMetadata(repoOwner, repoName, `ENV_FILE_${appNameUpper}`, username);
        }
    }
    /**
     * Commit multiple files to repository in a single commit
     */
    async commitFiles(owner, repo, branch, files, username) {
        const commitMessage = 'Add Docker deployment configuration\n\n' +
            'This commit adds Dockerfile and GitHub Actions workflow for automated Docker deployment via ServerCompass.';
        console.log(`[GitHubActionsDockerService] Committing ${files.length} files in a single commit...`);
        try {
            const commitResult = await this.githubApi.createOrUpdateMultipleFiles(owner, repo, branch, files, commitMessage, username);
            if (commitResult.changed) {
                console.log(`[GitHubActionsDockerService] ✓ Committed ${files.length} file(s): ${files.map(f => f.path).join(', ')}`);
            }
            else {
                console.log('[GitHubActionsDockerService] ℹ️ Files unchanged; no commit created.');
            }
            return commitResult;
        }
        catch (error) {
            console.error(`[GitHubActionsDockerService] Failed to commit files:`, error);
            throw error;
        }
    }
    /**
     * Setup docker-compose.yml on VPS
     */
    async setupVPS(options) {
        const { serverId, projectName, repoOwner, repoName, appPath, port, containerPort, envFileContent, imageTag, includeTraefikPublicNetwork, } = options;
        const composeContent = this.generateDockerCompose({
            projectName,
            repoOwner,
            repoName,
            port,
            containerPort,
            imageTag,
            includeTraefikPublicNetwork,
        });
        const quotedAppPath = this.shellQuote(appPath);
        // Create app directory and docker-compose.yml
        await this.sshService.executeCommand(serverId, `mkdir -p ${quotedAppPath}`);
        await this.sshService.executeCommand(serverId, `cat > ${quotedAppPath}/docker-compose.yml << 'EOF'\n${composeContent}\nEOF`);
        if (envFileContent !== undefined) {
            const envDelimiter = `SERVER_COMPASS_ENV_${Date.now()}`;
            await this.sshService.executeCommand(serverId, `cat > ${quotedAppPath}/.env << '${envDelimiter}'\n${envFileContent}\n${envDelimiter}`);
        }
        else {
            await this.sshService.executeCommand(serverId, `touch ${quotedAppPath}/.env`);
        }
        console.log(`[GitHubActionsDockerService] Created docker-compose.yml at ${appPath}`);
    }
    /**
     * Get server connection details from database
     */
    getServerDetails(serverId) {
        const server = db_1.db
            .prepare('SELECT host, username, port FROM servers WHERE id = ? LIMIT 1')
            .get(serverId);
        if (!server) {
            throw new Error('Server not found');
        }
        return server;
    }
    /**
     * Wait for GitHub Actions workflow to complete
     */
    async waitForDeployment(repoOwner, repoName, timeoutMs = 600000) {
        const startTime = Date.now();
        const minCreatedAt = startTime - 2 * 60 * 1000; // allow clock skew and brief setup delays
        let pollInterval = 20000; // Start with 20 second intervals (reduces API calls)
        let consecutiveErrors = 0;
        let lastStatus = '';
        let pollCount = 0;
        let monitoredRunId = null;
        console.log(`[GitHubActionsDockerService] Starting workflow polling for ${repoOwner}/${repoName} (interval: ${pollInterval / 1000}s)`);
        while (Date.now() - startTime < timeoutMs) {
            try {
                const runs = await this.githubApi.getWorkflowRuns(repoOwner, repoName, { per_page: 10 });
                if (runs.length > 0) {
                    const eligibleRuns = runs.filter(workflowRun => workflowRun.conclusion !== 'skipped');
                    const selectedRun = monitoredRunId
                        ? eligibleRuns.find(workflowRun => workflowRun.id === monitoredRunId)
                        : eligibleRuns.find(workflowRun => new Date(workflowRun.created_at).getTime() >= minCreatedAt);
                    if (selectedRun) {
                        if (!monitoredRunId) {
                            monitoredRunId = selectedRun.id;
                            console.log(`[GitHubActionsDockerService] 🎯 Tracking run #${selectedRun.run_number} (${selectedRun.event} event)`);
                        }
                        pollCount++;
                        // Only log when status changes
                        const runId = `${selectedRun.status}:${selectedRun.conclusion || 'null'}`;
                        if (runId !== lastStatus) {
                            console.log(`[GitHubActionsDockerService] 📊 Monitoring run #${selectedRun.run_number} (${selectedRun.event} event) - ${selectedRun.status}${selectedRun.conclusion ? ` (${selectedRun.conclusion})` : ''} (poll #${pollCount})`);
                            lastStatus = runId;
                        }
                        if (selectedRun.status === 'completed') {
                            if (selectedRun.conclusion === 'success') {
                                console.log(`[GitHubActionsDockerService] ✅ Workflow completed successfully after ${pollCount} polls`);
                                return { success: true, url: selectedRun.html_url };
                            }
                            else {
                                console.log(`[GitHubActionsDockerService] ❌ Workflow failed with conclusion: ${selectedRun.conclusion}`);
                                return {
                                    success: false,
                                    error: `Workflow failed with conclusion: ${selectedRun.conclusion}`,
                                    url: selectedRun.html_url,
                                };
                            }
                        }
                    }
                    else if (pollCount === 0) {
                        console.log(`[GitHubActionsDockerService] Waiting for workflow run to start...`);
                    }
                }
                else if (pollCount === 0) {
                    console.log(`[GitHubActionsDockerService] No workflow runs found yet, waiting...`);
                }
                // Reset error counter on successful poll
                consecutiveErrors = 0;
                pollInterval = 10000; // Reset to normal interval
                // Wait before next poll
                await new Promise((resolve) => setTimeout(resolve, pollInterval));
            }
            catch (error) {
                console.error('[GitHubActionsDockerService] Error polling workflow:', error.message || error);
                // Check if it's a rate limit error
                if (error.status === 403 || error.status === 429) {
                    consecutiveErrors++;
                    // If we hit rate limits multiple times, give up
                    if (consecutiveErrors >= 3) {
                        return {
                            success: false,
                            error: this.formatGitHubError(error),
                            url: `https://github.com/${repoOwner}/${repoName}/actions`,
                        };
                    }
                    // Exponential backoff with rate limit
                    const retryAfter = error.response?.headers?.['retry-after'];
                    const waitTime = retryAfter ? parseInt(retryAfter) * 1000 : Math.min(60000 * consecutiveErrors, 120000);
                    console.log(`[GitHubActionsDockerService] Rate limited. Waiting ${waitTime / 1000}s before retry...`);
                    await new Promise((resolve) => setTimeout(resolve, waitTime));
                }
                else {
                    // For other errors, use exponential backoff
                    consecutiveErrors++;
                    pollInterval = Math.min(pollInterval * 2, 60000); // Max 60 seconds
                    await new Promise((resolve) => setTimeout(resolve, pollInterval));
                }
            }
        }
        return {
            success: false,
            error: '⏱️ Deployment monitoring timed out.\n\n' +
                'This doesn\'t mean the deployment failed - it\'s still running in the background.\n\n' +
                '💡 Next steps:\n' +
                '• Check the GitHub Actions tab to see the current status\n' +
                '• The workflow typically takes 5-10 minutes to complete\n' +
                '• You\'ll receive a notification when it finishes',
            url: `https://github.com/${repoOwner}/${repoName}/actions`,
        };
    }
}
exports.GitHubActionsDockerService = GitHubActionsDockerService;
const createGitHubActionsDockerService = (sshService) => new GitHubActionsDockerService(sshService);
exports.createGitHubActionsDockerService = createGitHubActionsDockerService;
//# sourceMappingURL=GitHubActionsDockerService.js.map