"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TraefikDynamicRouter = void 0;
exports.createTraefikDynamicRouter = createTraefikDynamicRouter;
/**
 * TraefikDynamicRouter - Manages instant traffic switching via Traefik's file provider
 *
 * Uses dynamic file config to switch traffic between containers without Traefik restart.
 * The file provider watches /etc/traefik/dynamic and auto-reloads on changes (~100ms).
 */
class TraefikDynamicRouter {
    sshService;
    constructor(sshService) {
        this.sshService = sshService;
    }
    /**
     * Get the dynamic config file path for a domain
     */
    getDynamicConfigPath(domain) {
        // Replace dots with dashes for filename safety
        const sanitizedDomain = domain.replace(/\./g, '-');
        return `/opt/traefik/dynamic/${sanitizedDomain}.yml`;
    }
    /**
     * Generate Traefik dynamic config YAML for routing to a container
     *
     * @param domain - The domain name (e.g., 'myapp.example.com')
     * @param containerName - The Docker container name to route to
     * @param port - The port the container is listening on
     * @param ssl - Whether to enable SSL (default: true)
     */
    generateDynamicConfig(domain, containerName, port, ssl = true) {
        const routerName = domain.replace(/\./g, '-');
        const serviceName = `${routerName}-service`;
        return `# Auto-generated by ServerCompass Zero-Downtime Deployer
# DO NOT EDIT - This file is managed automatically

http:
  routers:
    ${routerName}:
      rule: "Host(\`${domain}\`)"
      service: ${serviceName}
      entryPoints:
        - websecure
      ${ssl ? `tls:
        certResolver: letsencrypt` : ''}

  services:
    ${serviceName}:
      loadBalancer:
        servers:
          - url: "http://${containerName}:${port}"
`;
    }
    /**
     * Switch traffic from current container to new container
     * Uses dynamic file config - no Traefik restart needed
     *
     * @param serverId - Server ID
     * @param domain - Domain to route
     * @param newContainer - New container name to route to
     * @param port - Port the container is listening on
     * @param ssl - Whether to enable SSL (default: true)
     */
    async switchTraffic(serverId, domain, newContainer, port, ssl = true) {
        const configPath = this.getDynamicConfigPath(domain);
        const configContent = this.generateDynamicConfig(domain, newContainer, port, ssl);
        // Write the dynamic config file using heredoc (single quotes prevent variable expansion)
        const command = `cat > '${configPath}' << 'TRAEFIKEOF'
${configContent}
TRAEFIKEOF`;
        const result = await this.sshService.executeCommand(serverId, command);
        if (result.exitCode !== 0) {
            throw new Error(`Failed to write Traefik dynamic config: ${result.stderr || result.stdout}`);
        }
        // Traefik auto-reloads (watch: true) - typically ~100ms
        // We can optionally verify the config was applied by checking Traefik's API
    }
    /**
     * Rollback traffic to previous container
     *
     * @param serverId - Server ID
     * @param domain - Domain to route
     * @param previousContainer - Previous container name to route to
     * @param port - Port the container is listening on
     * @param ssl - Whether to enable SSL (default: true)
     */
    async rollbackTraffic(serverId, domain, previousContainer, port, ssl = true) {
        // Rollback is the same as switch - just point to different container
        await this.switchTraffic(serverId, domain, previousContainer, port, ssl);
    }
    /**
     * Remove dynamic config for a domain
     * Use this when deleting a stack or cleaning up after failed deployment
     *
     * @param serverId - Server ID
     * @param domain - Domain to remove config for
     */
    async removeDynamicConfig(serverId, domain) {
        const configPath = this.getDynamicConfigPath(domain);
        await this.sshService.executeCommand(serverId, `rm -f '${configPath}' 2>/dev/null || true`);
    }
    /**
     * Check if a dynamic config exists for a domain
     *
     * @param serverId - Server ID
     * @param domain - Domain to check
     */
    async hasDynamicConfig(serverId, domain) {
        const configPath = this.getDynamicConfigPath(domain);
        const result = await this.sshService.executeCommand(serverId, `test -f '${configPath}' && echo "exists" || echo "none"`);
        return result.stdout.trim() === 'exists';
    }
    /**
     * Get the current container target from dynamic config
     *
     * @param serverId - Server ID
     * @param domain - Domain to check
     * @returns Container name or null if no config exists
     */
    async getCurrentTarget(serverId, domain) {
        const configPath = this.getDynamicConfigPath(domain);
        const result = await this.sshService.executeCommand(serverId, `cat '${configPath}' 2>/dev/null | grep -oP 'url: "http://\\K[^:]+' | head -1`);
        const containerName = result.stdout.trim();
        return containerName || null;
    }
}
exports.TraefikDynamicRouter = TraefikDynamicRouter;
// Factory function
function createTraefikDynamicRouter(sshService) {
    return new TraefikDynamicRouter(sshService);
}
//# sourceMappingURL=TraefikDynamicRouter.js.map